version: "3.7"
services:
  hub:
    container_name: django-starter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8020:8020
    volumes:
      - ./project/:/project/
      - ./main/:/main/
      - ./img/:/img/
    environment:
      DEBUG: 1
      SECRET_KEY: yellowpolkadotbikini
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: django-starter-postgres
      POSTGRES_PORT: 5432

  postgres:
    container_name: django-starter-postgres
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
