version: "3.7"

volumes:
  postgres_data:

services:
  postgres:
    container_name: django-starter-postgres
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
  hub:
    container_name: django-starter
    depends_on:
      - postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8020:8020
    volumes:
      - ./project/:/project/
      - ./main/:/main/
      - ./img/:/img/
    env_file:
      - .env.dev
